# Generated by Django 4.2.2 on 2024-08-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studing", "0001_initial"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studing.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
