# Generated by Django 4.2.2 on 2024-08-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_paid_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Наличные"), (2, "Перевод на счёт")],
                null=True,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
