# Generated by Django 4.2.2 on 2024-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку для оплаты",
                max_length=400,
                null=True,
                unique=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор сессии для оплаты через сервисы оплаты",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "Наличные"), (2, "Перевод на счёт")],
                default=2,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="summ_of_payment",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
