# Generated by Django 4.2.2 on 2024-08-26 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="summ_of_payment",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сумма оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
