# Generated by Django 4.2.2 on 2024-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studing", "0003_subscriptiononcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID продукта для stripe",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID продукта для stripe",
            ),
        ),
    ]
